name: Build and Test on Pull Request

permissions:
  contents: read
  pull-requests: read

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - develop
  workflow_call:
  workflow_dispatch:

jobs:
  build-test:
    concurrency:
      group: build-test-${{ github.ref }}-${{ matrix.task }}
      cancel-in-progress: true
    name: Build and Test (${{ matrix.task }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: [build, test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 #v4.0.0
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run ${{ matrix.task }}
        run: |
          if [ "${{ matrix.task }}" == "build" ]; then
            pnpm run build
          else
            pnpm run test
          fi

  build-test-completed:
    name: Build and Test
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Mark Build and Test as Successful
        run: echo "All build and test tasks completed successfully."
